### PR TITLE
enhance metrics-collector deploy update check with api equality package.

### PR DESCRIPTION
**Pull request by morvencao**
This PR does:

1. Replace deployment equal check from `reflect.DeepEqual` to `apiequality`, because there are some noisy fields added by the apiserver, which results the check always return true.
2. Remove the test case for no clusterVersion, do we still need the case for openshift 3.11?  

Signed-off-by: morvencao <lcao@redhat.com>

### CODE REVIEW

**Comment by marcolan018** [comment]
@morvencao 
why we need to remove the case for 3.11?
OCP 3.11 is still in the support matrix in 2.3

**Comment by morvencao** [comment]
ok @marcolan018 
let me revert change for ocp 3.11 case.

**Pull request merged**
