### PR TITLE
update controller-runtime to prevent deprected message

### PR DESCRIPTION
**Pull request by songleo**
https://github.com/open-cluster-management/backlog/issues/13261
Signed-off-by: Song Song Li <ssli@redhat.com>

### CODE REVIEW

**Comment by clyang82** [comment]
it was updated to 0.9.0 in this PR - https://github.com/open-cluster-management/endpoint-metrics-operator/pull/99

**Comment by songleo** [comment]
Test with the latest version, upgrade to 0.9.0 is works well. close this PR.

**Pull request closed without merging**
